# Any database connection attributes set in `ENV["DATABASE_URL"]` override
# the configurations here. See Rails behavior:
#
#   https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database
#
# The staging and production environments rely exclusively
# on this connection URl to be set and are not defaulted here.
#
# An example postgres connection string is:
#
#   postgres://username:password@hostname/dbname?key1=val1
#   e.g postgres://girder:12345@localhost/girder_production?pool=5
#
# Other databases (MySQL, SQLite3, etc...) have their own formats specified
# in their documentation.

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  pool: <%= ENV.fetch('POSTGRES_CONNECTION_POOL', 5) %>
  timeout: <%= ENV.fetch('POSTGRES_TIMEOUT', 5000) %>

test:
  <<: *default
  # On test we specify a single `DATABASE_URL` to avoid having to specify
  # individual connection components. This will override any individual
  # components set (e.g. host, port, etc...)
  url: <%= ENV["DATABASE_URL"] %>
  database: girder_test

development:
  <<: *default
  database: girder_development

staging:
  <<: *default
  database: girder_staging

production:
  <<: *default
  database: girder
